@startuml
digraph root {
			fontname=Monospace
			fontsize=9
			subgraph "cluster_source" {
				 label="jknkj";
				 pencolor="invis";
			     "«p.name» : «p.type.name»"
			     [fontsize=9, fontname=Monospace, penwidth=1, shape=record, color=GREEN, fillcolor="WHITE", label="{ a | b | c }",style=filled]
			     "«p.name» : «p.type.name»" -> "idForPattern(p.target)" [fontname=Monospace, penwidth=1, color=GREEN, label="SDSDS", fontsize=8, constraint=true];
			}
			subgraph "cluster_target" {
				 label="";
				 pencolor="invis";
				 
			}
			subgraph "correspondence" {
				 label="";
				 pencolor="invis";
				 
			}
		}
@enduml